version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: laravel_test-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - webserver
            - db
        networks:
            - laravel_test

    db:
        image: mysql:8.0
        container_name: laravel_test-db
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: laravel_test_app
            MYSQL_ROOT_PASSWORD: laravel_root
            MYSQL_PASSWORD: laravel_test_app_password
            MYSQL_USER: laravel_test_app_user
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - laravel_test

    webserver:
        image: nginx:alpine
        container_name: laravel_test-nginx
        restart: unless-stopped
        tty: true
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel_test

networks:
    laravel_test:
        driver: bridge
